name: Inference Engine CI Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Inference Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-venv
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test Application
        run: python3 test_inference.py

      - name: Upload Test Results to Azure Blob
        run: |
          az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --container-name test-results \
            --file test_results.json \
            --name "results-$(date +%Y%m%d%H%M%S).json"

      - name: Docker Build and Push to ACR
        run: |
          echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login actionimage.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin
          docker build -t actionimage.azurecr.io/inference-engine:latest .
          docker push actionimage.azurecr.io/inference-engine:latest

      - name: Docker Run Container
        run: |
          docker pull actionimage.azurecr.io/inference-engine:latest
          docker run -d --name inference-engine -p 5000:5000 actionimage.azurecr.io/inference-engine:latest

      - name: Download Test Tool from Blob
        run: |
          az storage blob download \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --container-name test-tools \
            --name inference_test_tool.py \
            --file inference_test_tool.py

      - name: Run Container Test
        env:
          INFERENCE_API_URL: "http://4.217.250.205:5000"
        run: python3 inference_test_tool.py --url $INFERENCE_API_URL

### 승인 절차 정의 (환경 사용)
  approval:
    runs-on: ubuntu-latest
    needs: ci
    environment:
      name: need-approvals 
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Approval Step
        run: echo "Deployment Approved!"

### 컨테이너 종료 단계 (승인 후 실행)
  stop-container:
    runs-on: self-hosted
    needs: approval
    steps:
      - name: Stop and Remove Container
        run: |
          docker stop inference-engine || true
          docker rm inference-engine || true
          docker logout actionimage.azurecr.io
