name: Inference Engine CI Pipeline

# 워크플로우 트리거: main 브랜치로의 푸시 또는 수동 실행
on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 수동 실행 허용

jobs:
  ci:
    runs-on: self-hosted  # Azure VM Runner 사용

    steps:

      ### 리포지토리 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v2

      ### 환경 설정
      - name: Setup Inference Environment
        run: |
          # python3-venv 패키지 설치
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-venv
          
          ### 가상 환경 생성
          python3 -m venv venv
          source venv/bin/activate

          python -m pip install --upgrade pip
          
          pip3 install -r requirements.txt

      ### 애플리케이션 테스트 실행
      - name: Test Application
        run: |
          python3 test_inference.py

      ### 테스트 결과 Blob 업로드 (test-results 컨테이너)
      - name: Upload Test Results to Azure Blob
        run: |
          az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --container-name test-results \
            --file test_results.json \
            --name "results-$(date +%Y%m%d%H%M%S).json"

      ### Docker 빌드 및 ACR로 푸시
      - name: Docker Build and Push to ACR
        run: |
          echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login actionimage.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin
          docker build -t actionimage.azurecr.io/inference-engine:latest .
          docker push actionimage.azurecr.io/inference-engine:latest

      ### Docker 컨테이너 실행
      - name: Docker Run Container
        run: |
          docker pull actionimage.azurecr.io/inference-engine:latest
          docker run -d --name inference-engine -p 5000:5000 actionimage.azurecr.io/inference-engine:latest

      ### Blob 스토리지에서 테스트 도구 다운로드
      - name: Download Test Tool from Blob
        run: |
          az storage blob download \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --container-name test-tools \
            --name inference_test_tool.py \
            --file inference_test_tool.py

      ### Docker 컨테이너에서 테스트 도구 실행
      - name: Run Container Test
        env:
          INFERENCE_API_URL: "http://4.217.250.205:5000/inference"
        run: |
          python3 inference_test_tool.py --url $INFERENCE_API_URL

      ### Docker 컨테이너 종료
      - name: Stop and Remove Container
        run: |
          docker stop inference-engine
          docker rm inference-engine
          docker logout actionimage.azurecr.io
